# Generated by Django 3.0.3 on 2020-05-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
