# Generated by Django 3.0.4 on 2020-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
