# Generated by Django 3.0.3 on 2020-04-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200428_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='department_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DepInfo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DepInfo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee'),
        ),
    ]
