# Generated by Django 3.0.4 on 2020-03-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200316_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_assignment',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Employee'),
        ),
    ]
