# Generated by Django 3.0.3 on 2020-05-02 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_emp_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extended_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='everyday_hours_ext',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='report',
            name='hours_reported_ext',
            field=models.IntegerField(null=True),
        ),
    ]
