# Generated by Django 3.0.4 on 2020-04-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200406_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
