# Generated by Django 3.0.4 on 2020-03-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tasks_assignment_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='tasks_assignment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='tasks_assignment',
            name='assigned_to',
            field=models.ManyToManyField(to='accounts.Employee'),
        ),
    ]
