# Generated by Django 3.0.4 on 2020-04-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_project_department_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager_name',
        ),
    ]
