# Generated by Django 3.0.4 on 2020-03-16 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200316_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_task', models.ManyToManyField(to='accounts.Tasks_Assignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Tasks')),
            ],
        ),
    ]
