# Generated by Django 3.0.3 on 2020-05-03 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200502_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='everyday_hours_ext',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hours_reported_ext',
        ),
        migrations.CreateModel(
            name='Report_extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('everyday_hours', models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator])),
                ('hours_reported', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Activity')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Employee')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
    ]
