# Generated by Django 3.0.4 on 2020-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_department_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
