# Generated by Django 3.0.4 on 2020-03-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeetasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetasks',
            name='task',
        ),
    ]
