# Generated by Django 3.0.3 on 2020-05-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200506_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report_extended',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
