# Generated by Django 3.0.4 on 2020-03-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200318_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='manager',
            new_name='manager_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='project',
            new_name='project_assigned',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_name',
        ),
    ]
