# Generated by Django 3.0.3 on 2020-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_report_extended_extended_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_extended',
            name='extended_hours',
        ),
        migrations.AddField(
            model_name='report',
            name='extended_hours',
            field=models.BooleanField(default=False),
        ),
    ]
