# Generated by Django 3.0.3 on 2020-05-27 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20200527_0832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logged_in_user',
            new_name='LoggedInUser',
        ),
    ]
