# Generated by Django 3.0.3 on 2020-05-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200527_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
