# Generated by Django 3.0.4 on 2020-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='time_left',
            field=models.IntegerField(null=True),
        ),
    ]
