# Generated by Django 3.0.4 on 2020-04-02 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_department_time_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_time',
        ),
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='everyday_hours',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='report',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
