# Generated by Django 3.0.4 on 2020-04-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200402_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
        ),
    ]
